#!/bin/bash
# run_all_steps.sh: the full step-6 pipeline, started detached by run_all.sh (log run_all.out). Do not edit this file
# while it runs (bash reads a running script incrementally). Keys are read from the environment only.
#   1. the committee calls of the asked batches (settings.yaml batches_to_ask; batch 1 only = 33 calls), 9 workers
#   2. a second pass that asks the calls still missing once more (valid calls are never re-asked)
#   3. collect -> integrate (claude-opus-5-5, one call per asked field) -> context notes -> pool -> cost
set -uo pipefail
cd "/project/jevans/Dawoon/Nobel Prize/Econ/06_candidates"
export LD_LIBRARY_PATH=/project/jevans/Dawoon/env/Curvature/lib
PY=/project/jevans/Dawoon/env/Curvature/bin/python           # by path: the login shell's hkg_venv must not be used
echo "== $(date '+%F %T') committee calls"
$PY virtual_committee.py run --workers 9
echo "== $(date '+%F %T') second pass: missing calls asked once more"
$PY virtual_committee.py run --workers 6 | grep -v "exists (not re-asked)"
$PY virtual_committee.py status
$PY virtual_committee.py collect
echo "== $(date '+%F %T') integrate: claude-opus-5-5, asked fields"
if $PY virtual_committee.py integrate; then
  $PY virtual_committee.py context && $PY virtual_committee.py pool
else
  echo "integrate incomplete; run again (integrated fields are kept): $PY virtual_committee.py integrate"
fi
$PY virtual_committee.py estimate | tail -1
echo "== $(date '+%F %T') done"
